import { BaseRepository } from "./base.repository";
import { Homepage, IHomepage } from "../models/Homepage";
import { About, IAbout } from "../models/About";
import { FounderJourney, IFounderJourney } from "../models/FounderJourney";
import { MissionVision, IMissionVision } from "../models/MissionVision";
import { WhatWeDo, IWhatWeDo } from "../models/WhatWeDo";
import { Service, IService } from "../models/Service";
import { Collaboration, ICollaboration } from "../models/Collaboration";
import { Campaign, ICampaign } from "../models/Campaign";
import { ProductLaunch, IProductLaunch } from "../models/ProductLaunch";
import { Event, IEvent } from "../models/Event";
import { Portfolio, IPortfolio } from "../models/Portfolio";
import { MediaGallery, IMediaGallery } from "../models/MediaGallery";
import { Career, ICareer } from "../models/Career";
import { Blog, IBlog } from "../models/Blog";
import { Faq, IFaq } from "../models/FAQ";
import { Contact, IContact } from "../models/Contact";
import { WebsiteSettings, IWebsiteSettings } from "../models/WebsiteSettings";

export const homepageRepository = new BaseRepository<IHomepage>(Homepage);
export const aboutRepository = new BaseRepository<IAbout>(About);
export const founderJourneyRepository = new BaseRepository<IFounderJourney>(FounderJourney);
export const missionVisionRepository = new BaseRepository<IMissionVision>(MissionVision);
export const whatWeDoRepository = new BaseRepository<IWhatWeDo>(WhatWeDo);
export const serviceRepository = new BaseRepository<IService>(Service);
export const collaborationRepository = new BaseRepository<ICollaboration>(Collaboration);
export const campaignRepository = new BaseRepository<ICampaign>(Campaign);
export const productLaunchRepository = new BaseRepository<IProductLaunch>(ProductLaunch);
export const eventRepository = new BaseRepository<IEvent>(Event);
export const portfolioRepository = new BaseRepository<IPortfolio>(Portfolio);
export const mediaGalleryRepository = new BaseRepository<IMediaGallery>(MediaGallery);
export const careerRepository = new BaseRepository<ICareer>(Career);
export const blogRepository = new BaseRepository<IBlog>(Blog);
export const faqRepository = new BaseRepository<IFaq>(Faq);
export const contactRepository = new BaseRepository<IContact>(Contact);
export const websiteSettingsRepository = new BaseRepository<IWebsiteSettings>(WebsiteSettings);
